name = "hlma-hono-workers"
main = "src/index.ts"
compatibility_date = "2026-04-09"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "1e1cc78b07c740078853667b06b3566e"